// <auto-generated />
using System;
using BasketBallLiveScore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BasketBallLiveScore.Migrations
{
    [DbContext(typeof(BasketballContext))]
    [Migration("20241227192725_AddNavigation")]
    partial class AddNavigation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-rc.2.24474.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BasketBallLiveScore.Models.BasketballGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Competition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GameNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuarterCount")
                        .HasColumnType("int");

                    b.Property<int>("QuarterDuration")
                        .HasColumnType("int");

                    b.Property<int>("SetupManagerId")
                        .HasColumnType("int");

                    b.Property<int?>("SpectatorCount")
                        .HasColumnType("int");

                    b.Property<int>("TimeoutDuration")
                        .HasColumnType("int");

                    b.Property<string>("Venue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SetupManagerId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("BasketBallLiveScore.Models.Foul", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgainstPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("BasketballGameId")
                        .HasColumnType("int");

                    b.Property<string>("Chrono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CommittingPlayerId")
                        .HasColumnType("int");

                    b.Property<string>("FoulType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quarter")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgainstPlayerId");

                    b.HasIndex("BasketballGameId");

                    b.HasIndex("CommittingPlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("Fouls");
                });

            modelBuilder.Entity("BasketBallLiveScore.Models.GameStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BasketballGameId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BasketballGameId");

                    b.ToTable("GameStaff");
                });

            modelBuilder.Entity("BasketBallLiveScore.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCaptain")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPlaying")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("PlayerTeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerTeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("BasketBallLiveScore.Models.PointsScored", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BasketballGameId")
                        .HasColumnType("int");

                    b.Property<string>("Chrono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("Quarter")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BasketballGameId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("PointsScored");
                });

            modelBuilder.Entity("BasketBallLiveScore.Models.Substitution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Chrono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerInId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerOutId")
                        .HasColumnType("int");

                    b.Property<int>("Quarter")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerInId");

                    b.HasIndex("PlayerOutId");

                    b.HasIndex("TeamId");

                    b.ToTable("Substitutions");
                });

            modelBuilder.Entity("BasketBallLiveScore.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BasketballGameId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LongCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BasketballGameId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("BasketBallLiveScore.Models.TeamStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StaffTeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StaffTeamId");

                    b.ToTable("TeamStaff");
                });

            modelBuilder.Entity("BasketBallLiveScore.Models.TimerState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BasketballGameId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentPeriod")
                        .HasColumnType("int");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("bit");

                    b.Property<int>("Minutes")
                        .HasColumnType("int");

                    b.Property<int>("QuarterCount")
                        .HasColumnType("int");

                    b.Property<int>("QuarterDuration")
                        .HasColumnType("int");

                    b.Property<int>("Seconds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BasketballGameId")
                        .IsUnique();

                    b.ToTable("TimerStates");
                });

            modelBuilder.Entity("BasketBallLiveScore.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("FirstName", "LastName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BasketBallLiveScore.Models.BasketballGame", b =>
                {
                    b.HasOne("BasketBallLiveScore.Models.User", "SetupManager")
                        .WithMany("GamesConfigured")
                        .HasForeignKey("SetupManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SetupManager");
                });

            modelBuilder.Entity("BasketBallLiveScore.Models.Foul", b =>
                {
                    b.HasOne("BasketBallLiveScore.Models.Player", "AgainstPlayer")
                        .WithMany("FoulsReceived")
                        .HasForeignKey("AgainstPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BasketBallLiveScore.Models.BasketballGame", "BasketballGame")
                        .WithMany("Fouls")
                        .HasForeignKey("BasketballGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BasketBallLiveScore.Models.Player", "CommittingPlayer")
                        .WithMany("FoulsCommitted")
                        .HasForeignKey("CommittingPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BasketBallLiveScore.Models.Team", "Team")
                        .WithMany("Fouls")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgainstPlayer");

                    b.Navigation("BasketballGame");

                    b.Navigation("CommittingPlayer");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BasketBallLiveScore.Models.GameStaff", b =>
                {
                    b.HasOne("BasketBallLiveScore.Models.BasketballGame", "BasketballGame")
                        .WithMany("GameStaff")
                        .HasForeignKey("BasketballGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BasketballGame");
                });

            modelBuilder.Entity("BasketBallLiveScore.Models.Player", b =>
                {
                    b.HasOne("BasketBallLiveScore.Models.Team", "PlayerTeam")
                        .WithMany("Players")
                        .HasForeignKey("PlayerTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerTeam");
                });

            modelBuilder.Entity("BasketBallLiveScore.Models.PointsScored", b =>
                {
                    b.HasOne("BasketBallLiveScore.Models.BasketballGame", "BasketballGame")
                        .WithMany("PointsScored")
                        .HasForeignKey("BasketballGameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BasketBallLiveScore.Models.Player", "Player")
                        .WithMany("PointsScored")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BasketBallLiveScore.Models.Team", "Team")
                        .WithMany("PointsScored")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BasketballGame");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BasketBallLiveScore.Models.Substitution", b =>
                {
                    b.HasOne("BasketBallLiveScore.Models.BasketballGame", "Game")
                        .WithMany("Substitutions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BasketBallLiveScore.Models.Player", "PlayerIn")
                        .WithMany("SubstitutionsIn")
                        .HasForeignKey("PlayerInId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BasketBallLiveScore.Models.Player", "PlayerOut")
                        .WithMany("SubstitutionsOut")
                        .HasForeignKey("PlayerOutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BasketBallLiveScore.Models.Team", "Team")
                        .WithMany("Substitutions")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("PlayerIn");

                    b.Navigation("PlayerOut");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BasketBallLiveScore.Models.Team", b =>
                {
                    b.HasOne("BasketBallLiveScore.Models.BasketballGame", "BasketballGame")
                        .WithMany("Teams")
                        .HasForeignKey("BasketballGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BasketballGame");
                });

            modelBuilder.Entity("BasketBallLiveScore.Models.TeamStaff", b =>
                {
                    b.HasOne("BasketBallLiveScore.Models.Team", "StaffTeam")
                        .WithMany("TeamStaff")
                        .HasForeignKey("StaffTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StaffTeam");
                });

            modelBuilder.Entity("BasketBallLiveScore.Models.TimerState", b =>
                {
                    b.HasOne("BasketBallLiveScore.Models.BasketballGame", "BasketballGame")
                        .WithOne("TimerState")
                        .HasForeignKey("BasketBallLiveScore.Models.TimerState", "BasketballGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BasketballGame");
                });

            modelBuilder.Entity("BasketBallLiveScore.Models.BasketballGame", b =>
                {
                    b.Navigation("Fouls");

                    b.Navigation("GameStaff");

                    b.Navigation("PointsScored");

                    b.Navigation("Substitutions");

                    b.Navigation("Teams");

                    b.Navigation("TimerState")
                        .IsRequired();
                });

            modelBuilder.Entity("BasketBallLiveScore.Models.Player", b =>
                {
                    b.Navigation("FoulsCommitted");

                    b.Navigation("FoulsReceived");

                    b.Navigation("PointsScored");

                    b.Navigation("SubstitutionsIn");

                    b.Navigation("SubstitutionsOut");
                });

            modelBuilder.Entity("BasketBallLiveScore.Models.Team", b =>
                {
                    b.Navigation("Fouls");

                    b.Navigation("Players");

                    b.Navigation("PointsScored");

                    b.Navigation("Substitutions");

                    b.Navigation("TeamStaff");
                });

            modelBuilder.Entity("BasketBallLiveScore.Models.User", b =>
                {
                    b.Navigation("GamesConfigured");
                });
#pragma warning restore 612, 618
        }
    }
}
